Missing #include
When compiling with NO_PLUGINS I get:
openmpt\soundlib\Snd_fx.cpp(5042): error C2653: 'MIDIEvents': is not a class or namespace name

Maybe lines around 5042 should have ifndef NO_PLUGINS instead